import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        //english
        'en_US': {
          'streax': 'Streax',
          'sign_up': 'Sign Up',
          'sign_in': 'Sign In',
          'welcome_back': 'Welcome back!',
          'glad_to_see': 'Glad to see you, Again!',
          'phone_no': 'Phone Number',
          'password': 'Password',
          'forgot_password?': 'Forgot Password?',
          'apple_sign_in': 'Continue with Apple',
          'google_sign_in': 'Continue with Google',
          'dont_have_account': 'Don’t have an account?',
          'user_exists': 'User Exists.',
          'already_have_account': 'Already have an account?',
          "message_forgot_password_phone":
              "Don't worry! It occurs. Please enter the phone number  linked with your account.",
          "message_forgot_password_email":
              "Don't worry! It occurs. Please enter the email address  linked with your account.",
          'send_otp': 'Send OTP',
          'forgot_password': 'Forgot Password',
          "remember_password": "Remember Password?",
          "otp_verification": "OTP Verification",
          "enter_verification_code_phone":
              "Enter the verification code we just sent on your phone number.",
          "enter_verification_code_email":
              "Enter the verification code we just sent on your email",
          "resend_code": "Resend code",
          "verify": "Verify",
          "create_new_password": "Create New Password",
          "hint_new_password":
              "Your new password must be unique from those previously used.",
          "new_password": "New Password",
          "confirm_password": "Confirm Password",
          "reset_password": "Reset Password",
          "password_changed": "Password Changed!",
          "password_change_successfully":
              "Your password has been\n changed successfully.",
          "back_to_sign_in": "Back to Sign In",
          "signup_to_get_started": "Sign Up to get\n started",
          "sign_up_with_email": "Sign Up with email address",
          "sign_up_with_phone": "Sign Up with phone number",
          "enter_valid_phone_number": "Please enter  a valid phone number",
          'message_password_helper':
              'Password must contain least one(uppercase,lowercase,digit,special character,) and minimum 8 characters',
          'message_enter_password': 'Please Enter Your Password',
          'message_enter_valid_password': 'Please enter a valid password',
          'message_enter_name': 'Please enter your name.',
          'message_enter_username': 'Please enter your username.',
          'message_enter_phone_number': 'Please enter your phone number',
          'message_enter_valid_phone_number':
              'Please enter a valid phone number.',
          "email_address": "Email Address",
          "male": "Male",
          "female": "FeMale",
          'message_enter_email': 'Please enter your email address.',
          'message_invalid_email': 'Please enter a valid email address.',
          'message_select_dob': 'Please select your date of birth.',
          'message_field_cannot_be_empty': 'This field can\'t be empty.',
          'name': 'Name',
          'username': 'Username',
          'birthday': 'Birthday',
          'gender': 'Gender',
          'interested_in': 'Interested In',
          "age": "Age",
          'distance_preference': 'Distance Preference',
          'age_preference': 'Age Preference',
          "next": "Next",
          'set_your_profile': "Set your Profile Photo",
          "work": "Work",
          "education": "Education",
          "lives_in": "Lives In",
          "from": "From",
          "hint_about_me": "Share something about yourself",
          "one_last_thing": "One Last Thing",
          "enter_phone_number": "Please Enter Your Phone Number",
          'phone_number': 'Phone Number',
          'add_more_optional': 'Add More (optional)',
          "you_want_to_skip": "Are you sure you want to skip? "
              "Our research shows user with intro"
              " video has 37% higher chances of "
              "getting matches.",
          'skip_for_now': 'Skip for now',
          'record_intro': 'Record Intro',
          'record_intro_video': 'Record a 5 to 15 seconds\n introduction video',
          'search': "Search",
          'alex': 'Alex Linderson',
          'how_are_you': 'How are you today?',
          '2_min': '2 min ago',
          'report': 'Report',
          'add': 'Add Story',
          'matches': 'Matches',
          'adelita_mia': 'Adelita Mia',
          'gadise_ava': 'Gadise Ava',
          'view_all': 'View All',
          'i_liked': 'I Liked',
          'more': 'More',
          'sameera': 'Sameera',
          'antonela_emma': 'Antonella Emma',
          'delete': 'Delete',
          'stories': 'Stories',
          'settings': 'Settings',
          'travel_mode': 'Travel Mode',
          'subscription_and_purchases': 'Subscription and Purchases',
          'account_type': 'Account Type',
          'crush': 'Crush',
          'center_stage': 'Center Stage',
          'instant_chat': 'Instant Chat',
          'no_plans': 'No Plan Activate',
          'not_available': 'Not Available',
          'notifications': 'Notifications',
          'change_password': 'Change Password',
          'update_mobile_number': 'Update Mobile Number',
          'legal_notice': 'Legal Notice',

          'mutual_match': 'Mutual Match',
          'liked_me': 'Liked Me',
          'chat': 'Chat',
          'old_password': 'Old Password',
          'current_password': 'Current Password',
          'support': 'Support',
          'privacy_policy': 'Privacy Policy',
          'terms_of_use': 'Terms of Use',
          'update': 'Update',
          'my_profile': 'My Profile',
          'hint_name': 'Full name or nickname',
          'hint_username': 'Choose a unique username',
          'please_enter_dob': 'Please enter your dob.',
          'select_gender': "Select Gender",
          'delete_account': 'Delete Account',
          'sign_in_with_phone': 'Sign In with phone number',
          'sign_in_with_email': 'Sign In with email address',
          'add_photo': 'Add Photo',
          'hint_work': 'Job title at your company',
          'hint_education': 'Degree and school name',
          'enter_current_address': 'Enter your current address',
          'enter_address': 'Enter your permanent address',
          'enter_phone': 'Enter phone number',
          "men": "Men",
          "women": "Women",
          "non_binary": "Non Binary",
          "man": "Man",
          "woman": "Woman",
          "everyone": "Everyone",
          "get_streax": "Get streax",
          "add_intro_video": "Add Intro Video",
          "student": "Student",
          "about_me": "About Me",
          "done": "Done",
          "cancel": "Cancel",
          "america": "America",
          "gallery": "Gallery",
          "upload_from_insta": "Upload from Instagram",
          "launch_camera": "Launch Camera",
          "upload_from_gallery": "Upload from Gallery",
          "sent_text":
              "Send a text without mutually\nmatching 5 per week with\n premium",
          "price": "1 for \$0.99",
          "let_me_know": "Let them know you crushing\n 10per week with premium",
          "ask": "Ask Out",
          "plans_and_request": "Plan and send a data request.",
          "premium_available": "Only available\n in premium.",
          "advances_algorithms":
              "Feature your profile for\n 1 hour to other users using\n our advances algorithms",
          "cities_and_countries":
              "Feature your location to\n match with people in other\n Cities/ Countries",
          "upgrade_premium_account":
              "Or,\nGet everything by upgrading to Streax ",
          "account_starting":
              "\nSubscription, starting only @ ",
          "loream_ipsum": "Lorem ipsum is placeholder text.",
          "select": "Select",
          "describe_yourself": "Describe Yourself in Few Lines",
          "go_premium": "Go Premium",
          "browse_subscription_plan": "Browse Subscription Plans",
          "take_a_photo": "Take a Photo",
          "choose_from_gallery": "Choose from Gallery",
          "most_popular": "Most Popular",
          "week": "Week",
          "or": "OR",
          "midwest_boarding_school": "Midwest Boarding School",
          "select_a_plan": "Select a  Plan",
          "hello": "Hello!",
          "start_type": "Start typing to search",
          "Buy": "buy",
          'email_already_exist': 'Email already exist',
          'phone_already_exist': 'Phone no already exist',
          'loading_please_wait': 'Loading...\nPlease wait!',
          'message_server_error':
              'We are Facing some issue.\nPlease try again!',
          'message_wrong_otp': 'You have entered a wrong OTP!',
          'basics': 'Basics',
          'pictures': 'Pictures',
          'few_extras': 'Few Extras',
          'hint_dob': '__/__/____',
          'message_select_gender': 'Please select gender',
          'message_select_interested_gender':
              'Please select the gender you are interested in.',
          'message_add_profile_image': 'Please add your profile image',
          'alert': 'Alert',
          'error': 'Error',
          'success': 'Success',
          'dismiss': 'Dismiss',
          'skip': 'Skip',
          'description_record_intro':
              'Record a 5 to 15 seconds introduction video',
          'retake': 'Retake',
          'forgot_with_email': 'Forgot with Email',
          'forgot_with_phone': 'Forgot with Phone',
          'error_loading_media': 'Error Loading Media',
          'edit_profile': 'Edit Profile',
          'save': 'Save',
          'deleted_user': 'Deleted User',
          'user': 'User',
          'add_story': 'Add Story',
          'like': 'Like',
          'nothing_to_show_here': 'Nothing to show here!',
          'preview': 'Preview',
          'take_again': 'Take Again',
          'post': 'Post',
          'new_post': 'New Post',
          'loading': 'Loading...',
          'my_story': 'My Story',
          'send': 'Send',
          'send_message': 'Send Message',
          'delete_this_story': 'Delete this story?',
          'message_sure_delete_post':
              'Deleting a story is irreversible. Are you absolutely sure you want to proceed?',
          'you_have_a_new_match': 'You have a\nNew Match',
          'say_hi': 'Say Hi',
          'maybe_later': 'Maybe Later',
          'mutual_matches': 'Mutual Matches',
          'unlike': 'Unlike',
          'unmatch': 'Unmatch',
          'block': 'Block',
          'unblock': 'Unblock',
          'message_block_user':
              'They won\'t be able to message you or find your profile on Streax.\nYou can unblock them at any time in the settings.',
          'message_unblock_user':
              'He will be able to message you or find your profile on Streax.',
          'story_views': 'Story Views',
          'all': 'All',
          'mutual': 'Mutual',
          'message_select_report_option': 'Please select report option.',
          'add_comment': 'Add Comment',
          'message_add_your_comment': 'Please add your comment.',
          'add_more': 'Add More',
          'minimum_2_images_gallery_required': 'Minimum 2 gallery images required.',
          'active_now': 'Active Now',
          'type_here': 'Type here...',
          'today': 'Today',
          'yesterday': 'Yesterday',
          'photo': 'Photo',
          'video': 'Video',
          'delete_for_me': 'Delete for me',
          'delete_for_everyone': 'Delete for everyone',
          'hangout': 'Hangout',
          'time': 'Time',
          'date': 'Date',
          'place': 'Hangout Spot',
          'hint_place': 'Where to? Enter a restaurant, park, etc.',
          'location': 'Location',
          'hint_address': ' Include the address.',
          'address': 'Address(Optional)',
          'hint_date': '__/__/____',
          'message_no_location_try_searching': 'No Locations.\nTry searching...',
          'message_loading_places':
              'Sit relaxed!!\n We are loading your places data.',
          'message_search_location': 'Search location...',
          'proceed': 'Proceed',
          'blocked': 'Blocked',
          'invited_you_on_date': 'invited you on a date!',
          'hangout_request': 'Hang out Request',
          'media': 'Media',
          'message_empty_blocked_list': 'No user in your blocked list!',
          'message_sure_unblock': 'Are you sure you want to unblock',
          'report_only': 'Report Only',
          'km': 'KM',
          'hint_password': '******',
          'deleting_account': 'Deleting Account?',
          'message_deleting_account': 'All data associated with your account, including account information and content, will be permanently deleted.You will lose access to Streax and will no longer be able to log in.Any subscriptions or services linked to your account will be terminated.If you are certain about deleting your account, please confirm by clicking the buttons below.',
          'message_password_must_be_same': 'Password does\'t matched',
          'password_changed_successfully': 'Password Changed Successfully.',
          'message_password_changed_successfully': 'Your password has been updated successfully. For security reasons, please log in again using your new credentials.Thank you for maintaining the security of your account.',
          'logout':'Logout',
          'message_logout':'This action will end your current session, and you will need to log in again to access your account.Are you sure you want to log out?',
          'message_enter_pin':'Please enter the pin sent to your\nregistered Email/Phone.',
          'sent':'Sent',
          'sent_story_comment':'Sent comment on story',
          'user_already_exists':'User already exists.',
          'image_cropper':'Image Cropper',
          'message_error_processing_image':'Facing error while processing image.Please try again!',
          'profile':'Profile',
          'miles':'Miles',
          'school':'School',
          'work_at':'Work At',
          'change':'Change',
          'title_request_location': 'So, are you from around here?',
          'description_request_location': 'Set your location to see who\'s in your area or beyond.You won\'t be able to match with people otherwise.',
          'allow':'Allow',
          'current_location':'Current Location',
          'search_location':'Search Location',
          'record':'Record',
          'requests':'Requests',
          'chat_requests':'Chat Requests',
          'accept':'Accept',
          'message_request_pending':'Your chat request is pending. You\'ll be able to send more messages once the other user accepts your request.',
          'buy':'Buy',
          'for':'For',
          'message_product_not_found':'Product not found!',
          'message_store_not_available':'Store not available!',
          'one_time_purchase':'One time Purchases',
          'message_no_subscription_plans_available':'No Subscription Plans Available!',
          'message_purchase_pending':'Your Purchase is in pending state',
          'message_purchase_error':'Getting error during purchase',
          'ask_out':'Ask Out',
          'no_plan_active':'No Plan Active',
          'available':'Available',
          'you_have_invited':'You have invited',
          'wants_to_hangout':' wants to hang out!',
          'on_a_date':'on a Date!',
          'to_hangout':'to hang out!',
          'username_not_available':'Username not available!',
          'video_trimmer':'Video Trimmer',
          'story':'Story',
          'i_am_18_years':'I am 17 years of age or older and agree to the ',
          'terms_of_services':'Terms of Service',
          'and':'and',
          'message_min_3_char_required':'Minimum 3 characters required.',
          'message_we_missed_you':'We missed you 🥰🥰',
          'message_lets_freaking_go':"Let's freaking gooo! 🤩😁",
          'lets_get_started':"Let's get started!",
          'subtitle_browse_store':"One time purchases or Subscriptions to get exclusive features",
          'streax_store':"Streax Store",
          'browse_store':"Browse Store",
          'available_only':"Available only",
          'on':"on",
          'subscription_plans':"Subscription Plans",
          'best_value':"Best Value",
          'subscription_disclaimer':"Features can change at any time. Payment will be charged to your App Store (for iOS) and Google Play (for Android) account. Your Subscription will auto renew at your selected interval until you cancel. Cancel anytime. By tapping “Subscribe”, you agree to the Streax Terms and Conditions and Auto Renewal",
          'subscriptions':"Subscriptions",
          'comment':"Comment",
          'subscribe':"Subscribe",
          'hint_lives_in':"Current city,state, and country",
          'hint_from_address':"Hometown, state, and country",
          'hang_out': 'Hang out',
          'add_a_message': 'Add a message',
          'log_in_to_streax': 'Log in to Streax',
          'activate': 'Activate',
          'allow_permissions': 'Allow Permissions',
          'go_to_settings':
          'Go to your app setting to enable permissions manually',
          'open_settings': 'Open Settings',
          'boost_visibility': 'Boost your visibility to ',
          'increase_chances_matching': ' and increase your chances of matching by upto 2x. You\'ll send a like, but only you\'ll know CenterStage is activated.Proceed?',
        },
      };
}
